/* Auto-generated by download_quiz.py */
const QUIZ_DATA = [
  {
    "id": 200981696,
    "position": 1,
    "type": "multiple_answers_question",
    "question": "<div class=\"question_text user_content\" id=\"question_200981696_question_text\">\n<p>What are the functions of the structure with the PURPLE arrows?</p>\n<p><img alt=\"image.png\" loading=\"lazy\" src=\"mollusks_images/qi_0001.jpg\"/></p>\n<p> </p>\n</div>",
    "images": [
      "qi_0001.jpg"
    ],
    "answers": [
      "defense",
      "locomotion",
      "Expel waste, water and debris (excurrent)",
      "filter feeding (aka suspension)",
      "reproduction - gametes leave via the excurrent siphon"
    ],
    "correct": [
      2,
      3,
      4
    ],
    "points": 1
  },
  {
    "id": 200981569,
    "position": 2,
    "type": "multiple_choice_question",
    "question": "<div class=\"question_text user_content\" id=\"question_200981569_question_text\">\n<p><img alt=\"image.png\" loading=\"lazy\" src=\"mollusks_images/qi_0002.jpg\"/></p>\n<p>The PURPLE arrows are pointing to what structures?</p>\n</div>",
    "images": [
      "qi_0002.jpg"
    ],
    "answers": [
      "anus and mouth",
      "feet",
      "incurrent and excurrent siphons",
      "ears"
    ],
    "correct": 2,
    "points": 1
  },
  {
    "id": 200980991,
    "position": 3,
    "type": "multiple_choice_question",
    "question": "<div class=\"question_text user_content\" id=\"question_200980991_question_text\">\n<p><img alt=\"image.png\" loading=\"lazy\" src=\"mollusks_images/qi_0003.jpg\"/></p>\n<p> </p>\n<p>Which side of the clam is the posterior?</p>\n</div>",
    "images": [
      "qi_0003.jpg"
    ],
    "answers": [
      "the part that the arrow is pointing towards",
      "the bottom part opposite the arrow",
      "the side with the green triangle",
      "the side with the red star"
    ],
    "correct": 3,
    "points": 1
  },
  {
    "id": 200981272,
    "position": 4,
    "type": "multiple_answers_question",
    "question": "<div class=\"question_text user_content\" id=\"question_200981272_question_text\">\n<p>Select all FUNCTIONS that apply to the structure at the RED arrow.</p>\n<p><img alt=\"image.png\" loading=\"lazy\" src=\"mollusks_images/qi_0004.jpg\"/></p>\n<p> </p>\n</div>",
    "images": [
      "qi_0004.jpg"
    ],
    "answers": [
      "digging",
      "anchoring",
      "locomotion",
      "reproduction",
      "feeding"
    ],
    "correct": [
      0,
      1,
      2
    ],
    "points": 1
  },
  {
    "id": 200982153,
    "position": 5,
    "type": "multiple_choice_question",
    "question": "<div class=\"question_text user_content\" id=\"question_200982153_question_text\">\n<p><img alt=\"image.png\" loading=\"lazy\" src=\"mollusks_images/qi_0005.jpg\"/></p>\n<p>PURPLE arrows is pointing to what structure?</p>\n</div>",
    "images": [
      "qi_0005.jpg"
    ],
    "answers": [
      "the rectum (next to the heart)",
      "the kidneys and bladder",
      "the mouth (next to the labial palps)",
      "the heart (next to the ostium)"
    ],
    "correct": 3,
    "points": 1
  },
  {
    "id": 200981456,
    "position": 6,
    "type": "multiple_answers_question",
    "question": "<div class=\"question_text user_content\" id=\"question_200981456_question_text\">\n<p><img alt=\"image.png\" loading=\"lazy\" src=\"mollusks_images/qi_0006.jpg\"/></p>\n<p>BLUE arrow is pointing at which structure?</p>\n</div>",
    "images": [
      "qi_0006.jpg"
    ],
    "answers": [
      "mouth and anus",
      "incurrent siphon",
      "excurrent siphon",
      "gonads",
      "gills",
      "intestine & rectum"
    ],
    "correct": [
      5
    ],
    "points": 1
  },
  {
    "id": 200980984,
    "position": 7,
    "type": "multiple_choice_question",
    "question": "<div class=\"question_text user_content\" id=\"question_200980984_question_text\">\n<p><img alt=\"image.png\" loading=\"lazy\" src=\"mollusks_images/qi_0007.jpg\"/></p>\n<p>The arrow is pointing at which structure?</p>\n</div>",
    "images": [
      "qi_0007.jpg"
    ],
    "answers": [
      "head",
      "umbo",
      "ventral side",
      "shell"
    ],
    "correct": 1,
    "points": 1
  },
  {
    "id": 200981036,
    "position": 8,
    "type": "multiple_choice_question",
    "question": "<div class=\"question_text user_content\" id=\"question_200981036_question_text\">\n<p><img alt=\"image.png\" loading=\"lazy\" src=\"mollusks_images/qi_0008.jpg\"/></p>\n<p>Which structure is being pointed at by the PURPLE arrow?</p>\n</div>",
    "images": [
      "qi_0008.jpg"
    ],
    "answers": [
      "gonads",
      "gills",
      "mantle cavity tissue",
      "digestive gland",
      "foot",
      "intestine & rectum"
    ],
    "correct": 2,
    "points": 1
  },
  {
    "id": 200981744,
    "position": 9,
    "type": "multiple_choice_question",
    "question": "<div class=\"question_text user_content\" id=\"question_200981744_question_text\">\n<p>RED arrow is pointing to what structure?</p>\n<p><img alt=\"image.png\" loading=\"lazy\" src=\"mollusks_images/qi_0009.jpg\"/></p>\n</div>",
    "images": [
      "qi_0009.jpg"
    ],
    "answers": [
      "foot",
      "poopy snot",
      "mantle",
      "gills"
    ],
    "correct": 0,
    "points": 1
  },
  {
    "id": 200981344,
    "position": 10,
    "type": "multiple_answers_question",
    "question": "<div class=\"question_text user_content\" id=\"question_200981344_question_text\">\n<p> </p>\n<p><img alt=\"image.png\" loading=\"lazy\" src=\"mollusks_images/qi_0010.jpg\"/></p>\n<p>The YELLOW arrow is pointing to what structure?</p>\n<p> </p>\n</div>",
    "images": [
      "qi_0010.jpg"
    ],
    "answers": [
      "digestive gland",
      "heart",
      "gonad",
      "intestine & rectum",
      "mantle cavity",
      "foot",
      "gills"
    ],
    "correct": [
      0
    ],
    "points": 1
  },
  {
    "id": 200981091,
    "position": 11,
    "type": "multiple_choice_question",
    "question": "<div class=\"question_text user_content\" id=\"question_200981091_question_text\">\n<p><img alt=\"image.png\" loading=\"lazy\" src=\"mollusks_images/qi_0011.jpg\"/></p>\n<p>What structure is being pointed at by the BLACK arrow?</p>\n</div>",
    "images": [
      "qi_0011.jpg"
    ],
    "answers": [
      "mantle cavity tissue",
      "gonads",
      "intestine & rectum",
      "foot",
      "digestive gland",
      "heart",
      "gills"
    ],
    "correct": 6,
    "points": 1
  },
  {
    "id": 200982236,
    "position": 12,
    "type": "multiple_choice_question",
    "question": "<div class=\"question_text user_content\" id=\"question_200982236_question_text\">\n<p><img alt=\"image.png\" loading=\"lazy\" src=\"mollusks_images/qi_0012.jpg\"/></p>\n<p>What is the function of the structure at the RED arrow?</p>\n</div>",
    "images": [
      "qi_0012.jpg"
    ],
    "answers": [
      "a powerful muscle for digging",
      "a powerful muscle for closing the shell super tight",
      "a powerful muscle for feeding",
      "a powerful muscle for opening the shell"
    ],
    "correct": 1,
    "points": 1
  },
  {
    "id": 200981858,
    "position": 13,
    "type": "multiple_choice_question",
    "question": "<div class=\"question_text user_content\" id=\"question_200981858_question_text\">\n<p><img alt=\"image.png\" loading=\"lazy\" src=\"mollusks_images/qi_0013.jpg\"/></p>\n<p>Besides gas exchange, what other function do the structures at the GREEN arrow perform?</p>\n</div>",
    "images": [
      "qi_0013.jpg"
    ],
    "answers": [
      "these are the gonads for making sperm and eggs",
      "they process nitrogenous waste like a kidney",
      "they use them to swim",
      "the cilia traps food particles brought into the mantle by the incurrent siphon and sends them to the mouth"
    ],
    "correct": 3,
    "points": 1
  },
  {
    "id": 200981748,
    "position": 14,
    "type": "multiple_choice_question",
    "question": "<div class=\"question_text user_content\" id=\"question_200981748_question_text\">\n<p><img alt=\"image.png\" loading=\"lazy\" src=\"mollusks_images/qi_0014.jpg\"/></p>\n<p>YELLOW arrow is pointing at which structure?</p>\n</div>",
    "images": [
      "qi_0014.jpg"
    ],
    "answers": [
      "mantle",
      "gills",
      "labial palps",
      "anus",
      "heart",
      "foot"
    ],
    "correct": 2,
    "points": 1
  },
  {
    "id": 200981829,
    "position": 15,
    "type": "multiple_choice_question",
    "question": "<div class=\"question_text user_content\" id=\"question_200981829_question_text\">\n<p><img alt=\"image.png\" loading=\"lazy\" src=\"mollusks_images/qi_0015.jpg\"/></p>\n<p> </p>\n<p>What is the function of the structure being pointed to with the YELLOW arrow?</p>\n</div>",
    "images": [
      "qi_0015.jpg"
    ],
    "answers": [
      "Lips on the mouth for feeding",
      "gills to trap food particles and send to the mouth",
      "kidneys for getting rid of nitrogenous waste",
      "excretion of waste - an anus",
      "heart for pumping blood to gills"
    ],
    "correct": 0,
    "points": 1
  },
  {
    "id": 200981186,
    "position": 16,
    "type": "multiple_choice_question",
    "question": "<div class=\"question_text user_content\" id=\"question_200981186_question_text\">\n<p><img alt=\"image.png\" loading=\"lazy\" src=\"mollusks_images/qi_0016.jpg\"/></p>\n<p>RED arrow is pointing at which structure?</p>\n</div>",
    "images": [
      "qi_0016.jpg"
    ],
    "answers": [
      "gonads",
      "digestive gland",
      "gills",
      "intestine & rectum",
      "foot",
      "mantle cavity tissue",
      "heart"
    ],
    "correct": 4,
    "points": 1
  },
  {
    "id": 200981397,
    "position": 17,
    "type": "multiple_answers_question",
    "question": "<div class=\"question_text user_content\" id=\"question_200981397_question_text\">\n<p><img alt=\"image.png\" loading=\"lazy\" src=\"mollusks_images/qi_0017.jpg\"/></p>\n<p>GREEN arrow is pointing at what structure?</p>\n</div>",
    "images": [
      "qi_0017.jpg"
    ],
    "answers": [
      "the one that makes digestive enzymes",
      "the mouth and rectum",
      "the hearts - clams have three",
      "the one that makes gametes (sperm and egg)"
    ],
    "correct": [
      3
    ],
    "points": 1
  }
];
