/* Explanations for every question, keyed by position number.
   Loaded by quiz.html and shown in the feedback box after each answer. */
const Q_EXPLANATIONS = {

  // ── PHYLOGENETICS ────────────────────────────────────────────────────────────
  1: "A paraphyletic group includes an ancestor and SOME (not all) of its descendants — it excludes one or more lineages that evolved from the same ancestor. Region B omits certain descendant lineages, making it paraphyletic rather than monophyletic.",
  2: "A paraphyletic group includes an ancestor and some of its descendants but excludes others. Region A here excludes certain descendant groups, fitting the paraphyletic definition.",
  3: "Linnean hierarchy (largest to smallest): Domain → Kingdom → Phylum → Class → Order → Family → Genus → Species. Class sits immediately below Phylum.",
  4: "Arthropoda is one of the major animal phyla — it ranks between Kingdom Animalia and Class (e.g., Insecta, Malacostraca). Phyla are defined by shared body plans.",
  5: "A monophyletic group (clade) includes exactly ONE common ancestor and ALL of its descendants — it's the 'natural' unit used in modern phylogenetics. Region B captures the ancestor and every descendant.",
  6: "A polyphyletic group is assembled from members of DIFFERENT ancestral lineages that do NOT share a unique common ancestor within the group. Region A draws members from separate, unrelated branches.",
  7: "Linnean hierarchy above Family: Order → Class → Phylum → Kingdom. Order is the rank immediately above Family.",
  110: "The most basal group sits at the base of the tree (deepest branch) and diverged first from the common ancestor. On a ladder-like cladogram, group A branches off before all others.",
  111: "A clade consists of one ancestral population plus ALL of its descendant populations — it is by definition monophyletic. Clades are the building blocks of modern (phylogenetic) classification.",
  112: "Cnidaria (jellyfish, corals, sea anemones, hydrozoans) is classified as a phylum — a major division of Kingdom Animalia defined by the shared presence of cnidocytes (stinging cells).",
  113: "The highlighted grouping shows one ancestor and all of its descendants with no exclusions, which is the definition of a clade (monophyletic group).",
  114: "Linnean hierarchy below Phylum: Class → Order → Family → Genus → Species. Class is the first rank below Phylum.",
  115: "Linnean hierarchy below Genus: Species is the only rank below Genus. Each species is the most specific category in the system.",
  116: "On a phylogenetic tree, the most closely related groups share the most recent common ancestor. D and E share a node that is more recent than any node D shares with A, B, or C.",
  117: "Linnean hierarchy above Family: Order → Class → Phylum. Order sits immediately above Family.",
  118: "This diagram shows a group that includes an ancestor and some but not all descendants — a hallmark of a paraphyletic grouping (e.g., 'Reptilia' without birds).",
  119: "This diagram draws members from separate branches that do not share an exclusive common ancestor, making it polyphyletic — the least natural phylogenetic grouping.",
  170: "In this cladogram, D and E share the most recent common node, so E is D's closest relative. Closeness = shared branch tips.",
  171: "Order sits directly above Family in the Linnean hierarchy. Mnemonic: King Philip Came Over For Good Soup (Kingdom, Phylum, Class, Order, Family, Genus, Species).",
  172: "A clade includes one ancestor and ALL descendants — it is monophyletic by definition. 'Clade' comes from the Greek for branch.",
  173: "A polyphyletic group contains members from multiple, separate lineages without a shared exclusive common ancestor. The diagram highlights taxa from non-adjacent branches.",
  174: "A monophyletic group (= clade) includes one ancestor and ALL of its descendants. The highlighted grouping in this diagram captures all descendants of the marked ancestor with no exclusions.",
  175: "Species is the most specific rank in Linnean classification — it sits directly below Genus and defines groups whose members can interbreed and produce fertile offspring.",
  176: "The most basal group is the one that branches off first (deepest node) from the rest. On this cladogram, A is the earliest-diverging group.",
  177: "Cnidaria is classified at the rank of Phylum in Linnean taxonomy, grouping all animals that share cnidocytes (nematocyst-bearing stinging cells).",
  178: "Class is the taxonomic rank immediately below Phylum. Examples: Phylum Arthropoda → Class Insecta; Phylum Cnidaria → Class Hydrozoa.",
  179: "A paraphyletic group includes an ancestor and some of its descendants — excludes at least one descendant lineage. The highlighted region in the paraphyletic diagram omits certain descendant taxa.",

  // ── CNIDARIA ─────────────────────────────────────────────────────────────────
  8:  "Sea anemones belong to Class Anthozoa ('flower animals') within Phylum Cnidaria. Anthozoans exist only as polyps — they lack a medusa stage. Other cnidarian classes include Scyphozoa (true jellyfish) and Hydrozoa.",
  9:  "The gastrovascular cavity is the central hollow space inside cnidarians where both digestion and distribution of nutrients occur. In Obelia (a hydrozoan), it runs through the entire colony.",
  10: "Cnidocytes are the specialized stinging cells unique to Phylum Cnidaria. Each contains a nematocyst (a coiled, barbed thread) that fires to capture prey or defend against predators.",
  11: "The polyp is the sessile (attached) body form of cnidarians — tubular, with the mouth and tentacles directed upward. Anthozoans (sea anemones) exist only as polyps.",
  12: "The gastrovascular cavity is the single internal chamber inside cnidarians that serves as both stomach and circulatory system, with only one opening (the mouth/anus).",
  13: "The medusa is the free-swimming, bell-shaped body form of cnidarians, with tentacles hanging downward and the mouth on the underside. Jellyfish (Scyphozoa) are medusae.",
  14: "Cnidaria is identified by radial symmetry, soft-bodied structure, and the presence of cnidocytes (stinging cells). Jellyfish are typical Scyphozoan medusae.",
  15: "Mesoglea is the gelatinous ('jelly') layer sandwiched between the outer epidermis and inner gastrodermis in cnidarians. It provides structural support and gives jellyfish their characteristic shape.",
  16: "This sea anemone belongs to Phylum Cnidaria — defined by having cnidocytes (stinging cells), radial symmetry, and a gastrovascular cavity. Sea anemones are Class Anthozoa.",
  120: "In the polyp/medusa diagram, label E indicates the gastrodermis — the inner cell layer lining the gastrovascular cavity, responsible for digestion. It corresponds to endoderm.",
  121: "The photo shows a jellyfish — a member of Phylum Cnidaria, identifiable by its bell-shaped medusa body form, tentacles, and radial symmetry.",
  122: "Label G on the polyp/medusa diagram marks the epidermis — the outer body wall layer, equivalent to ectoderm. It provides protection and houses the cnidocytes.",
  123: "The free-swimming, bell-shaped animal in the photo is the medusa form. Scyphozoan jellyfish spend most of their life cycle as medusae.",
  126: "Label B on the cnidarian anatomy diagram indicates the gonad — the reproductive organ that produces gametes (eggs or sperm). In cnidarians, gonads are typically located in the gastrodermis or epidermis.",
  127: "Label C in the polyp/medusa diagram indicates the tentacles — flexible appendages armed with cnidocytes used to capture prey and transfer food to the mouth.",
  128: "In this matching image, the left picture shows a polyp (sessile, tubular, mouth upward) and the right picture shows a medusa (bell-shaped, free-swimming, mouth downward).",
  130: "Label A on the cnidarian polyp diagram marks the mouth/anus — the single opening of the gastrovascular cavity. Cnidarians have only one body opening that serves both intake and excretion.",
  131: "Label A on the cnidarian anatomy diagram indicates the tentacles — the long, flexible appendages surrounding the mouth that bear cnidocytes for prey capture.",
  132: "Label D in the polyp/medusa diagram indicates the gastrovascular cavity — the central digestive space, also called the coelenteron, with a single opening.",
  133: "Label A on the sponge anatomy diagram marks the osculum — the large single opening at the top of the sponge through which filtered water exits. Distinct from the many small ostia (intake pores).",
  134: "Label B marks the spongocoel — the large central cavity inside the sponge body. Water flows in through the ostia, through choanocyte chambers, and out through the osculum.",
  135: "The arrows point to cnidocytes — the specialized stinging cells unique to Phylum Cnidaria. Each cnidocyte contains a nematocyst that fires a barbed thread when triggered.",
  180: "The sessile, tubular animal with tentacles pointing upward is a polyp — the attached body form of cnidarians. The hydroid colony slide shows cnidarian polyps.",
  181: "The arrows point to cnidocytes (also acceptable: nematocysts) — the stinging cells embedded in the tentacles and body wall of cnidarians. They fire coiled threads to paralyze prey.",
  182: "Label A on the cnidarian anatomy diagram marks the tentacles — the long, flexible arms bearing cnidocytes that surround the mouth opening in both polyp and medusa forms.",
  183: "The free-swimming, bell-shaped organism is the medusa body form. The jellyfish slide shows a Scyphozoan cnidarian in its dominant medusa stage.",
  184: "This Hydrozoa slide shows Obelia or a similar hydrozoan — identifiable by the colonial polyp structure with feeding polyps (gastrozooids). Class Hydrozoa is characterized by having both polyp and medusa stages.",
  185: "The image shows a jellyfish — a member of Phylum Cnidaria. Key cnidarian features: radial symmetry, cnidocytes, gastrovascular cavity, no true organs.",
  186: "Label B on the cnidarian anatomy diagram indicates the gonads — reproductive organs located in the body wall of cnidarians, producing eggs or sperm that are released into the water for fertilization.",

  // ── PORIFERA ─────────────────────────────────────────────────────────────────
  69: "The organism in the image is a sponge, which belongs to Phylum Porifera ('pore-bearers'). Sponges are sessile, asymmetrical filter feeders with no true tissues.",
  70: "Ostia are the numerous small pores on the outer surface of sponges through which water enters. Water is then filtered by choanocytes (collar cells) as it flows toward the spongocoel and out the osculum.",
  71: "Sponges are filter feeders (suspension feeders) — they draw water through their pores, and choanocytes trap bacteria, detritus, and organic particles from the passing current.",
  72: "The spongocoel is the large central cavity of a simple sponge. Water flows in through the ostia, past the choanocytes, and collects in the spongocoel before exiting through the osculum.",
  73: "The osculum is the single large opening at the top of the sponge through which filtered water exits. Water enters via many small ostia and exits through the single osculum.",
  74: "Choanocytes (collar cells) are the flagellated cells lining the spongocoel and canals of sponges. Their flagella create water currents, and the collar filters food particles from the passing water.",
  124: "Label E on the sponge anatomy diagram marks the ostia — the small pores covering the sponge body through which incoming water (carrying food particles and oxygen) enters.",
  125: "Label F marks the choanocytes — flagellated 'collar cells' that line the interior and drive water flow while capturing food particles. Unique to sponges and used as evidence of animal ancestry.",
  129: "Label C marks the amoebocytes — mobile cells in the mesohyl (middle layer) of sponges. They transport nutrients, secrete spicules (skeletal elements), and can differentiate into other cell types.",

  // ── NEMATODA ─────────────────────────────────────────────────────────────────
  20: "Female nematodes are larger than males. The red arrow points to the larger female (Ascaris can grow to 35 cm) and the yellow arrow to the smaller, often curved male. Males also have a curved tail with copulatory spicules.",
  22: "In the Ascaris dissection, the large coiled tubes labeled A are the uteri — where fertilized eggs are stored before being expelled. The uterus connects the oviduct to the vagina.",
  24: "The large, straight tube labeled A in the Ascaris dissection is the intestine — a long tube running the length of the worm that absorbs nutrients from digested food.",
  27: "The structures labeled B in the Ascaris dissection are the oviducts — tubes that carry eggs from the ovaries to the uterus. In Ascaris females, the oviducts are tightly coiled.",
  28: "Structure A in the Ascaris dissection is the intestine, whose function is digestion and nutrient absorption — it absorbs food and nutrients from ingested material.",
  29: "The purple arrow points to the testes — the paired, coiled male gonads of a nematode. Sperm produced here travel through the vas deferens (ductus deferens) to the cloaca.",
  31: "The red arrow points to the ductus deferens (vas deferens) — the tube carrying sperm from the testes to the cloaca in male nematodes.",
  34: "Structure A in the Ascaris dissection is the uterus, which stores eggs after fertilization. Ascaris females may contain up to 200,000 eggs per day — all stored in the uterus before expulsion.",
  35: "Ascaris lumbricoides is a roundworm belonging to Phylum Nematoda. Key features: pseudocoelom, cuticle, no circular muscles, tapered cylindrical body.",
  195: "In the nematode dissection, structure A is the oviduct — the narrow tube connecting the ovary to the uterus. Oviducts carry mature eggs toward the uterus.",
  196: "Structure B in the nematode dissection is the intestine — the broad central tube visible in dissection that runs the length of the worm for nutrient absorption.",
  197: "Structure C in the nematode dissection is the uterus — the expanded tube that stores eggs after fertilization, distinguishable from the oviduct by its larger diameter.",
  198: "The image shows a roundworm — Phylum Nematoda, identifiable by its smooth, unsegmented, cylindrical body with tapering ends and a tough cuticle. They have a pseudocoelom.",

  // ── ARTHROPODA ───────────────────────────────────────────────────────────────
  17: "Phylum Arthropoda is characterized by a jointed exoskeleton (cuticle), segmented body, and paired jointed appendages. The image shows an arthropod (insect or crustacean).",
  18: "The arthropod shown is identifiable by its jointed exoskeleton, segmented body, and multiple paired jointed appendages. Arthropoda is the largest animal phylum.",
  19: "Ants belong to Class Insecta within Phylum Arthropoda. Key insect features: 3 body segments (head, thorax, abdomen), 3 pairs of legs, 1 pair of antennae, and usually wings.",
  21: "The green gland is the main excretory organ of crustaceans — it filters blood and excretes waste as a dilute urine, opening at the base of the antennae. Analogous to kidneys.",
  23: "The cardiac stomach is the anterior (front) stomach of the crayfish digestive system. It contains ossicles (teeth) for grinding food and is located just posterior to the mouth.",
  25: "The pyloric stomach is the posterior stomach of the crayfish — it filters ground food and passes it to the digestive gland (hepatopancreas) for enzyme secretion and absorption.",
  26: "The heart of the crayfish is a muscular organ in the thorax that pumps hemolymph (blood). It is dorsal and receives blood from sinuses through ostia (small openings).",
  30: "The gills of the crayfish are feathery respiratory organs located in the gill chambers under the carapace. They extract dissolved oxygen from water as water flows over them.",
  32: "Male crayfish can be identified by the presence of two hard, modified pleopods (gonopods) near the base of the abdomen used to transfer sperm. Females have a broader abdomen and lack gonopods.",
  33: "The red arrow points to the intestine — the tube running from the pyloric stomach through the abdomen to the anus, responsible for final digestion and absorption.",
  36: "The digestive gland (hepatopancreas) is the large, spongy organ flanking the stomach in crayfish. It secretes digestive enzymes and absorbs nutrients — analogous to the liver + pancreas.",
  199: "Structure B in the labeled crayfish diagram is the cephalothorax — the fused head and thorax covered by the carapace. The cephalothorax houses the major organs and bears the walking legs and chelipeds.",
  200: "The blue arrow points to the rostrum — the pointed, beak-like projection at the front of the crayfish carapace between the eyes. It provides protection and may aid in water flow.",
  201: "Phylum Arthropoda: jointed exoskeleton, segmented body, paired jointed appendages. The image shows an arthropod (likely an insect or crustacean).",
  202: "The black arrow points to the telson — the flat, paddle-like terminal segment at the very end of the abdomen. With the uropods it forms the tail fan used for rapid backward swimming.",
  203: "Structure C on the labeled crayfish diagram marks the walking legs — the four pairs of thoracic legs used for locomotion. They are distinct from the chelipeds (front claws) and swimmerets.",
  204: "The green arrow brackets the abdomen — the posterior, segmented section of the crayfish body. It contains the gut, reproductive organs, and bears the swimmerets (pleopods).",
  205: "The red bracket indicates the walking legs — the four pairs of legs used for forward locomotion on the substrate. They are uniramous (single-branched) appendages.",
  206: "Structure A on the labeled crayfish diagram is the cheliped — the large, clawed first appendage of the crayfish used for defense, food capture, and courtship. It bears the distinctive large claw (chela).",
  207: "The yellow arrows point to the uropods — the flat, fan-shaped lateral appendages flanking the telson at the tail. Together, the uropods + telson form the tail fan for escape swimming.",
  208: "Arthropoda: jointed exoskeleton, segmented body, jointed appendages. The image shows an arthropod — identifiable by its rigid exoskeleton and visible jointed limbs.",

  // ── ANNELIDA ─────────────────────────────────────────────────────────────────
  40: "Phylum Annelida (segmented worms): body divided into ring-like segments (metameres) visible externally, have a true coelom, setae (bristles), and a closed circulatory system.",
  47: "The clitellum is the swollen, saddle-like band near the anterior end of an earthworm. It is a reproductive structure that secretes a mucus cocoon for eggs during mating.",
  52: "Leeches belong to Phylum Annelida — they are segmented worms (Class Hirudinea). Key features: segmented body, suckers at each end, and a reduced coelom. Leeches lack setae.",
  54: "Polychaete worms belong to Phylum Annelida (Class Polychaeta). They are distinguished by parapodia (paddle-like appendages bearing numerous setae/bristles) on each segment.",
  59: "Structure A in the earthworm dissection is the gizzard — the muscular, thick-walled organ that grinds soil. It lies posterior to the crop in the anterior digestive system.",
  60: "Structure A (red line) in the earthworm dissection is the dorsal blood vessel — the main vessel running along the dorsal surface. Blood flows anteriorly through it. In earthworms, this vessel is contractile.",
  61: "Structure B in the earthworm dissection is the crop — the thin-walled, expandable storage pouch anterior to the gizzard. It temporarily holds ingested soil before passing it to the muscular gizzard for grinding.",
  62: "Structure B in the earthworm dissection is the seminal vesicle (testis sac) — the large, white, lobed structures near the anterior end that store and mature sperm produced by the testes.",
  63: "Structure A in the squid dissection is the ovary — the female gonad producing eggs, located in the posterior mantle cavity of the squid.",
  64: "The red structures labeled B in the earthworm dissection are the hearts (aortic arches) — the 5 pairs of muscular tubes encircling the esophagus in segments 7–11. They pump blood ventrally.",
  65: "Structure A in the earthworm dissection is the seminal receptacles (spermathecae) — paired sacs in segments 9–10 that receive and store sperm from a mating partner.",
  193: "Phylum Annelida: segmented body with ring-like metameres, closed circulatory system, true coelom, setae (bristles). The polychaete worm slide shows a segment-bearing body with parapodia.",
  194: "The hairs labeled A on the polychaete slide are setae (also called chaetae) — chitinous bristles projecting from each segment of annelids. In polychaetes, they are clustered on parapodia for locomotion.",
  222: "Opening A in the earthworm diagram is the mouth — the anterior opening of the earthworm's digestive tract, located at the tip of the prostomium (the small lobe above the first segment).",
  223: "Structure A in the earthworm dissection is the seminal vesicle — the large, white, lobed reproductive organ storing and maturing sperm. It is one of the most prominent structures visible in earthworm dissection.",
  224: "Phylum Annelida: visible segmentation (ring-like annuli), setae, true coelom. The slide shows an annelid worm identifiable by its clearly segmented body.",
  225: "Structure C in the earthworm diagram is the clitellum — the distinctive swollen, saddle-shaped band encircling the body near segments 32–37. It produces the cocoon during reproduction.",
  226: "Phylum Annelida: segmented body, closed circulatory system, setae, true coelom. The slide shows an annelid (likely an earthworm) with visible segmentation.",
  227: "Opening B in the earthworm diagram is the anus — the posterior opening of the digestive tract, located at the very last segment (pygidium) of the earthworm.",
  228: "Structure B in the earthworm dissection is the gizzard — the muscular, thick-walled grinding chamber posterior to the crop. It crushes soil particles mechanically to release organic material.",
  229: "Earthworms (Phylum Annelida) have a TRUE coelom — a body cavity completely lined by mesoderm-derived peritoneum. This distinguishes them from pseudocoelomates (like nematodes) and acoelomates (like flatworms).",

  // ── MOLLUSCA ─────────────────────────────────────────────────────────────────
  37: "Snails/slugs belong to Class Gastropoda ('belly-footed') of Phylum Mollusca — characterized by a single, often coiled shell, muscular foot, and a radula for feeding.",
  38: "Cuttlefish belong to Phylum Mollusca — identified by their soft body, internal shell (cuttlebone), tentacles, and siphon. They are Class Cephalopoda.",
  41: "Snails/gastropods belong to Phylum Mollusca — identifiable by their single shell (or absence of shell in slugs), muscular foot, and mantle.",
  46: "Chitons belong to Phylum Mollusca, Class Polyplacophora. They are identified by 8 overlapping dorsal shell plates (valves) and a broad, flat muscular foot for clinging to rocks.",
  49: "Cuttlefish are Class Cephalopoda ('head-footed') of Phylum Mollusca — defined by a head surrounded by tentacles, an internal shell (cuttlebone), and a siphon for jet propulsion.",
  55: "The black arrow points to the arms — the 8 short, broad, sucker-bearing appendages of the squid. Arms differ from the 2 longer tentacles (which have suckers only at the tips).",
  56: "Structure B in the squid dissection is the tentacle — one of the 2 long, club-tipped appendages with suckers concentrated at the tip used for prey capture. Squids have 8 arms + 2 tentacles.",
  57: "Structure B in the squid dissection is the testis — the male gonad that produces sperm in the squid. In male squid, the testis is a compact white organ in the posterior mantle cavity.",
  58: "Structure A in the squid image is the beak — the hard, chitinous jaw structure at the center of the squid's tentacle circle, used to bite and tear prey. It resembles a parrot's beak.",
  66: "The red arrows in the squid dissection point to the gills (ctenidia) — the feathery respiratory organs in the mantle cavity of squid. Water flows over the gills via siphon-driven ventilation.",
  67: "Structure A in the squid dissection is the siphon (funnel) — the muscular tube in cephalopods through which water is forcefully expelled for jet propulsion and also for releasing ink.",
  68: "The red arrow in the squid image points to the mantle cavity — the space between the mantle and visceral mass in cephalopods. The gills and reproductive/excretory openings are located here.",
  191: "Phylum Mollusca: soft body, muscular foot, mantle that may secrete a shell. The slide shows a mollusk (likely a bivalve or gastropod).",
  192: "Phylum Mollusca: soft-bodied invertebrates with a mantle and usually a shell. The slide shows a mollusk (cuttlefish or squid = Cephalopoda).",
  217: "Structure A in the cephalopod diagram is the arm — one of the 8 short, sucker-bearing appendages of the octopus/squid. Arms differ from tentacles (longer, with suckers only at the tip).",
  218: "Structure C in the cephalopod diagram is the mantle — the muscular body wall that encloses the visceral organs and generates the water current through the mantle cavity in cephalopods.",
  219: "Phylum Mollusca: soft body, mantle, muscular foot (or tentacles in cephalopods). The slide shows a mollusk — identifiable by soft body parts and/or shell.",
  220: "Structure D in the cephalopod diagram is the siphon — the muscular funnel through which water is expelled for jet propulsion. The direction of the siphon controls the direction of movement.",
  221: "Phylum Mollusca: soft body, mantle, shell (often). The slide shows a cephalopod (likely squid or cuttlefish) — a member of Phylum Mollusca.",

  // ── PLATYHELMINTHES ──────────────────────────────────────────────────────────
  39: "Structure A in the tapeworm proglottid image is the ovary — the female reproductive organ producing eggs. In tapeworm proglottids, the ovary is typically bilobed and located in the posterior half.",
  42: "Structure A in the tapeworm proglottid is the genital pore — the opening on the side of the proglottid through which sperm enter (or eggs exit). Each mature proglottid has one.",
  43: "The slide shows a planarian — a free-living flatworm (Phylum Platyhelminthes, Class Turbellaria). Identified by its flat, leaf-like shape, eyespots, and auricles (ear-like lobes).",
  44: "Structure B (the bracket) in the tapeworm image is a proglottid — a single reproductive unit of the tapeworm body (strobila). Each proglottid contains both male and female organs.",
  45: "Structure B at the anterior end of the tapeworm is the rostellum — the retractable crown of hooks on the scolex (head) used to anchor to the host's intestinal wall.",
  48: "Structure B in the tapeworm proglottid is the testes — the multiple small, spherical male gonads scattered throughout the proglottid. They produce sperm that travels to the vagina through the vas deferens.",
  50: "The slide shows a planarian flatworm — Phylum Platyhelminthes (flat body, acoelomate, no anus, gastrovascular cavity). Planarians are free-living turbellarians.",
  51: "The slide shows a tapeworm — Phylum Platyhelminthes, Class Cestoda. Tapeworms are endoparasites identifiable by their ribbon-like strobila made of repeated proglottids.",
  53: "Structure A at the anterior end of the tapeworm is the scolex — the attachment 'head' of the tapeworm bearing suckers and/or hooks (rostellum) for anchoring to the host intestine.",
  187: "Structure A in the tapeworm proglottid is the ovary — the female reproductive organ. In mature proglottids, it is typically bilobed and located near the posterior end of the proglottid.",
  188: "Structure B in the tapeworm proglottid is the testes — numerous small, round male gonads scattered throughout the proglottid. Multiple testes per proglottid is typical of cestodes.",
  189: "Phylum Platyhelminthes: flat, unsegmented body, acoelomate, bilateral symmetry. The slide shows a flatworm (planarian, tapeworm, or fluke).",
  190: "The blue box in the tapeworm proglottid image outlines a proglottid — the fundamental repeating unit of the tapeworm. Each contains complete sets of both male and female reproductive organs.",
  209: "These images show flatworms — Phylum Platyhelminthes, identifiable by their flat, ribbon-like or leaf-like bodies, bilateral symmetry, no body cavity (acoelomate), and no anus.",
  210: "Planarians (free-living flatworms, Class Turbellaria) are carnivores that actively hunt small invertebrates, worms, and insects. They extend their pharynx to engulf prey.",
  211: "The purple arrow points to the pharynx — the muscular feeding tube that the planarian can extend through its ventral mouth to engulf and pull in prey. It is the central structure in planarian feeding.",
  212: "Free-living flatworms (turbellarians) inhabit moist terrestrial environments, marine habitats, and freshwater — wherever they can stay moist. They cannot survive in the desert (desiccation risk).",
  213: "Tapeworms (Class Cestoda) are intestinal parasites — they live in the digestive tract of vertebrate hosts, absorbing nutrients directly through their tegument (no digestive system).",
  214: "Flukes (Class Trematoda) are parasites that feed within the host's body — typically in the blood, liver, lungs, or intestines of vertebrates. They have a mouth and digestive system (unlike tapeworms).",
  215: "Mesenchyme (parenchyma) fills the space between skin and gut in flatworms — it is a loosely organized connective tissue of cells + collagen fibers. Flatworms are acoelomate (no true body cavity).",
  216: "The red arrow points to the gastrovascular cavity (intestine) — the branched digestive cavity of the planarian. It lacks an anus; undigested food is expelled back through the mouth.",

  // ── EMBRYOLOGY ───────────────────────────────────────────────────────────────
  75: "In the sea star gastrulation diagram, marker B indicates the ectoderm — the outermost primary germ layer forming from cells that remain on the surface. Ectoderm gives rise to skin and nervous system.",
  76: "Stage A in the sea star development series is the gastrula — identifiable by invagination of cells to form the archenteron (primitive gut). The gastrula has 3 germ layers.",
  77: "Stage D in the sea star development series is the fertilized egg (zygote) — a single large cell with a visible nucleus, prior to cleavage. It is diploid (2n) having just been fertilized.",
  78: "Label E in the sea star development diagram points to the blastocoel — the fluid-filled cavity inside the blastula. In the gastrula, the blastocoel is partially displaced by the growing archenteron.",
  79: "Stage B in the sea star development series is the blastula — a hollow ball of cells with a large central blastocoel cavity. It forms after cleavage divisions of the fertilized egg.",
  80: "Marker C in the sea star gastrulation diagram indicates the endoderm — the innermost germ layer formed by invagination (gastrulation). Endoderm lines the archenteron and gives rise to the digestive tract lining.",
  81: "Marker D in the sea star gastrulation diagram indicates the mesoderm — the middle germ layer (between ectoderm and endoderm). Mesoderm gives rise to muscle, connective tissue, circulatory system, and notochord.",
  82: "Letter C in the sea star development diagram marks the blastopore — the opening at the point of invagination during gastrulation. In deuterostomes (like sea stars and vertebrates), the blastopore becomes the anus.",
  83: "Letter A in the sea star gastrulation diagram marks the gastrocoel (archenteron) — the cavity formed by gastrulation that becomes the future digestive tract. The gastrocoel is lined by endoderm.",
  84: "The paired blocks flanking the neural tube in the chick embryo cross-section are somites — segmented blocks of paraxial mesoderm. Somites give rise to vertebrae, skeletal muscle of the trunk, and dermis.",
  160: "Stage A in the sea star development series is the gastrula — at this stage, cells have invaginated to form the archenteron (primitive gut), establishing the 3 germ layers (ectoderm, mesoderm, endoderm).",
  161: "Stage D in the sea star development series is the fertilized egg — a single large cell (zygote) that is 2n (diploid). It precedes cleavage and marks the start of embryonic development.",
  162: "Letter C in the sea star development diagram marks the blastopore — the initial opening of the archenteron formed during gastrulation. In deuterostomes, the blastopore becomes the anus.",
  163: "Marker C in the sea star gastrulation diagram indicates the endoderm — the innermost germ layer lining the archenteron (gastrocoel). Endoderm forms the gut lining, liver, pancreas, and lungs.",
  164: "The paired structures in the chick embryo cross-section are somites — paired blocks of paraxial mesoderm flanking the neural tube. They are the segmental units that generate vertebrae, trunk muscles, and dermis.",
  165: "Letter E in the sea star development diagram marks the blastocoel — the fluid-filled hollow cavity inside the blastula. It is the space enclosed by the blastula cell layer.",
  166: "Marker B in the sea star gastrulation diagram indicates the ectoderm — the outermost germ layer. Ectoderm gives rise to the epidermis of the skin, the nervous system, and sensory organs.",
  167: "Letter A in the sea star gastrulation diagram marks the gastrocoel (archenteron) — the embryonic gut cavity formed by invagination during gastrulation. It becomes the digestive tract.",
  168: "Marker D in the sea star gastrulation diagram indicates the mesoderm — the middle germ layer between ectoderm and endoderm. Mesoderm forms muscles, bones, kidneys, heart, and the notochord.",
  169: "Stage B in the sea star development series is the blastula — a hollow ball of cells surrounding the blastocoel. It is formed by repeated cleavage of the fertilized egg without growth.",

  // ── HISTOLOGY ────────────────────────────────────────────────────────────────
  85: "The nervous tissue slide is identifiable by large neurons with long processes (axons and dendrites) and smaller supporting glial cells. No other tissue type has this appearance.",
  86: "Cell B in the blood smear is an erythrocyte (red blood cell) — identified by its distinctive biconcave, disc shape and lack of a nucleus in mammals. They are by far the most numerous blood cells.",
  87: "The primary cell type in the hyaline cartilage slide is the chondrocyte — round cells sitting in lacunae (spaces) within the glassy, homogeneous matrix (chondrin). No visible vasculature.",
  88: "The adipose tissue slide shows loose connective tissue containing large vacuolated cells — each adipocyte is filled with a large fat droplet that pushes the nucleus to the periphery.",
  89: "Blood is a fluid connective tissue with a liquid extracellular matrix (plasma). The blood smear is identifiable by the liquid matrix and the presence of erythrocytes, leukocytes, and platelets.",
  90: "Fiber B in the loose areolar connective tissue slide is the elastin fiber — thinner, darker, and more wavy/irregular than collagen fibers. Elastin fibers allow connective tissue to stretch and recoil.",
  91: "Cell A in the blood smear is a leukocyte (white blood cell) — identified by its large, lobed or round nucleus (unlike anucleate erythrocytes). Leukocytes are part of the immune system.",
  92: "The tissue at the top of the skin slide is epithelial tissue — a sheet of cells forming a boundary layer. Identifiable by cells tightly packed in one or more layers with no extracellular space between them.",
  93: "The loose areolar connective tissue slide is identifiable by scattered fibroblasts, abundant ground substance, and loosely arranged collagen (wavy, thick) and elastin (thin, dark) fibers.",
  94: "The skeletal muscle slide shows identifiable long, multinucleated cells (fibers) with visible cross-striations (alternating light and dark bands). Voluntary and attached to bones via tendons.",
  95: "The cells in the bone slide are osteocytes — mature bone cells trapped in lacunae within the hard calcified matrix (osteons/Haversian systems). They maintain bone tissue.",
  96: "The bone slide shows supporting connective tissue identifiable by its hard, calcified matrix organized into concentric rings (osteons/Haversian systems) around central (Haversian) canals.",
  97: "The pancreatic duct slide shows simple cuboidal epithelium — a single layer of cube-shaped cells with round, central nuclei. Found in kidney tubules, thyroid follicles, and small ducts.",
  98: "The blood vessel slide shows simple squamous epithelium (endothelium) — a single layer of flat, scale-like cells with flattened nuclei. Allows efficient exchange of gases and nutrients.",
  99: "The skin epidermis slide shows stratified squamous epithelium — multiple layers of cells where the surface cells are flat and squamous. Provides abrasion resistance.",
  100: "Cell A in the nervous tissue slide is a neuron — the large, star-shaped cell with a prominent nucleus, cell body (soma), and long processes (axons/dendrites) visible under the microscope.",
  101: "The cartilage slide shows connective tissue. All connective tissues share: cells scattered in an extracellular matrix of fibers + ground substance. Cartilage ECM is firm but flexible.",
  102: "Cell A in the loose areolar connective tissue slide is a fibroblast — the most common connective tissue cell. It synthesizes and secretes collagen, elastin, and ground substance of the ECM.",
  103: "The hyaline cartilage slide shows supporting connective tissue with a glass-like (hyaline) matrix of collagen type II embedded in chondroitin sulfate. Found in joints, tracheal rings, nose, ears.",
  104: "Fiber C in the loose areolar connective tissue slide is collagen fiber — thick, wavy, pink-staining fibers arranged in bundles. Collagen provides tensile strength; it is the most abundant protein in the body.",
  105: "The trachea slide shows simple columnar epithelium — a single layer of tall, column-shaped cells with elongated nuclei at the base. Often has cilia (in trachea) and goblet cells for mucus.",
  106: "The small intestine wall slide shows smooth muscle — involuntary, non-striated spindle-shaped cells with a single central nucleus. Forms the walls of hollow organs (gut, blood vessels, bladder).",
  107: "Cell B in the nervous tissue slide is a glial cell (neuroglia) — the small, dark supporting cells of nervous tissue. They outnumber neurons, provide structural support, myelinate axons, and maintain homeostasis.",
  108: "The cardiac muscle slide shows involuntary, striated, branching cells joined by intercalated discs (dark cross-bands). Each cell has 1–2 nuclei. Found only in the heart.",
  109: "The skeletal muscle slide shows voluntary, striated, multinucleated long fibers. Cross-striations (sarcomere pattern) and peripheral nuclei distinguish it from cardiac and smooth muscle.",

  // ── HISTOLOGY FIMB duplicates (same images, same explanations) ───────────────
  136: "Cell A in the nervous tissue slide is a neuron — the large, star-shaped cell with a prominent nucleus and visible processes (axons/dendrites). Neurons are the signal-conducting cells of the nervous system.",
  137: "The hyaline cartilage slide shows glass-like supporting connective tissue with chondrocytes in lacunae within a homogeneous matrix. Found in tracheal rings, joint surfaces, and respiratory tract.",
  138: "The cartilage slide shows connective tissue — one of the four major tissue types. Connective tissue features cells scattered in an extensive extracellular matrix (ECM).",
  139: "Cell B in the blood smear is an erythrocyte (red blood cell) — biconcave, anucleate disc. Packed with hemoglobin for O₂ transport; most numerous cell in blood.",
  140: "The pancreatic duct slide is lined by simple cuboidal epithelium — single layer of cube-shaped cells, round central nucleus. Characteristic of secretory ducts and kidney tubules.",
  141: "The skin slide shows stratified squamous epithelium — multiple layers, surface cells are flat (squamous). The outermost layer is keratinized in skin to resist abrasion and water loss.",
  142: "Fiber C in the loose areolar connective tissue slide is a collagen fiber — thick, wavy, eosinophilic (pink) bundle. Collagen provides tensile strength to connective tissue (tendons = 100% dense collagen).",
  143: "The trachea slide shows simple columnar epithelium — single layer of tall column-shaped cells with basally located elongated nuclei. Cilia and goblet cells are often visible.",
  144: "The tissue at the top of the skin slide is epithelial tissue — cells tightly packed in layers forming a surface lining. Epithelium rests on a basal lamina above connective tissue.",
  145: "The skeletal muscle slide shows voluntary striated muscle with long, multinucleated fibers. The regular striations are caused by the repeating sarcomere pattern of actin and myosin.",
  146: "The cells in the bone slide are osteocytes — mature bone cells in lacunae of calcified matrix, connected by canaliculi. They are the main maintenance cells of bone.",
  147: "The primary cell in the hyaline cartilage slide is the chondrocyte — found in lacunae (round spaces) in the cartilage matrix. Chondrocytes maintain and produce the cartilage ECM.",
  148: "The bone slide shows compact bone — identifiable by circular osteons (Haversian systems) with osteocytes in lacunae, concentric lamellae, and a central Haversian canal containing blood vessels.",
  149: "Cell A in the loose areolar connective tissue slide is a fibroblast — spindle-shaped cell with an ovoid nucleus. The primary cell of loose connective tissue, responsible for ECM production.",
  150: "Fiber B in the loose areolar connective tissue slide is an elastin fiber — thin, dark, irregular fibers that allow tissue to stretch and recoil. Distinguished from collagen by being thinner, darker, and non-wavy.",
  151: "The blood smear shows blood — fluid connective tissue with a liquid ECM (plasma). The visible cells are erythrocytes (biconcave, anucleate) and leukocytes (nucleated).",
  152: "The small intestine wall slide shows smooth muscle — involuntary, non-striated spindle cells. The arrow points to the muscularis layer; smooth muscle lacks visible striations.",
  153: "The nervous tissue slide shows nervous tissue — identifiable by large neurons with long processes and smaller supporting glial cells. The tissue is highly cellular with minimal ECM.",
  154: "The loose areolar connective tissue slide shows loosely arranged collagen and elastin fibers, scattered fibroblasts, abundant ground substance. The most widely distributed CT in the body.",
  155: "Cell B in the nervous tissue slide is a glial cell (neuroglia) — small supporting cell with a dark nucleus and minimal cytoplasm. Glial cells are far more numerous than neurons and serve many support functions.",
  156: "The skeletal muscle slide shows muscle tissue — one of the four major tissue types. Muscle tissue is specialized for contraction and is characterized by visible striations.",
  157: "The blood vessel slide shows simple squamous epithelium — a single layer of flat cells (squamous) with flattened nuclei. Lines blood and lymph vessels (endothelium) and body cavities (mesothelium).",
  158: "Cell A in the blood smear is a leukocyte (white blood cell) — distinguished by its large, stainable nucleus. Leukocytes defend the body against infection.",
  159: "The cardiac muscle slide shows involuntary striated muscle with branching fibers joined by intercalated discs. Found only in the heart; intermediate characteristics between skeletal and smooth.",

  // ── SUPPLEMENTAL HISTOLOGY (quiz_data_extra.js positions 230-235) ─────────────
  230: "Goblet cells are flask-shaped mucus-secreting unicellular glands embedded within simple columnar epithelium. Their secretions form a protective mucous layer in the gut (jejunum) and trachea.",
  231: "Goblet cells are characteristic of simple columnar epithelium — found lining the small intestine, large intestine, trachea, and bronchi. They are not found in stratified squamous epithelium.",
  232: "The basal lamina (basement membrane) is a thin, acellular sheet of ECM proteins (laminin, type IV collagen, fibronectin) secreted by epithelial cells and underlying fibroblasts. It physically anchors the epithelium.",
  233: "All epithelial tissues rest on a basal lamina — it anchors them to the underlying connective tissue and acts as a selective barrier. It is not found surrounding individual muscle fibers or as part of blood.",
  234: "Dense connective tissue has tightly packed, parallel collagen fibers with very few cells (mainly fibroblasts) and minimal ground substance. High collagen density = great tensile strength — found in tendons, ligaments, and the outer ring of tracheal cartilage.",
  235: "Dense connective tissue has more collagen fibers packed tightly and fewer cells per unit area compared to loose areolar CT. Loose areolar CT has more ground substance and scattered fibers.",

  // ── SUPPLEMENTAL EMBRYOLOGY (quiz_data_extra.js positions 236-247) ──────────
  236: "The unfertilized egg (oocyte) precedes the fertilized egg in development. It is haploid (n) and must be fertilized by sperm to become a diploid (2n) zygote that begins cleavage.",
  237: "The unfertilized egg is haploid (n) because it has completed meiosis — the specialized two-division process that halves the chromosome number from 2n to n. Mitosis produces identical 2n daughter cells and does NOT halve the chromosome number.",
  238: "The neural plate is a flat, thickened sheet of dorsal ectoderm that appears during the early neurula stage. It is induced by the underlying notochord and is the precursor structure to the neural tube.",
  239: "The neural plate (flat, not yet folded) is the defining feature of the early neurula stage. In the late neurula, the neural plate has rolled up and fused into the neural tube.",
  240: "The neural tube forms when the edges (neural folds) of the neural plate roll upward, fold inward, and fuse along the dorsal midline to create a hollow tube — the precursor to the brain and spinal cord.",
  241: "The closed, hollow neural tube is the defining structure of the late neurula stage. In the early neurula, the neural plate is flat; by the late neurula, it has completely fused into a tube.",
  242: "Somites are paired, segmental blocks of paraxial mesoderm that flank the neural tube. They are visible in chick embryo cross-sections and give rise to vertebrae, skeletal muscles of the trunk, and dermis.",
  243: "The notochord is a firm, rod-like mesodermal structure running longitudinally beneath the neural tube. It provides structural support in the embryo and secretes signals that induce the overlying ectoderm to form the neural plate.",
  244: "In adult vertebrates, the notochord is largely replaced by the vertebral column (spine). Remnants persist as the nucleus pulposus at the center of each intervertebral disc.",
  245: "The neural plate and neural tube are derived from ectoderm — specifically, dorsal ectoderm overlying the notochord. The notochord induces this overlying ectoderm to thicken and fold inward.",
  246: "The notochord in chordate embryos (including frogs) is mesodermal in origin. It is an axial mesoderm structure that forms during gastrulation and lies beneath the future neural tube.",
  247: "The correct developmental sequence is: unfertilized egg → fertilized egg (zygote) → cleavage → blastula → gastrula → early neurula → late neurula. Each stage is defined by specific structural landmarks.",

  // ── SUPPLEMENTAL: ARTHROPODA ────────────────────────────────────────────────
  248: "The carapace is the hard dorsal shield that covers and protects the cephalothorax (the fused head + thorax region) of crustaceans. It is distinct from the cephalothorax itself, which is the body region — the carapace is the exoskeletal plate covering it.",

  // ── MOLLUSCA: CLAM ANATOMY (Q249–Q265) ──────────────────────────────────────
  249: "The excurrent siphon expels water, waste, debris, and gametes outward from the mantle cavity. Defense is a shell/adductor function; locomotion is the foot's job. The siphons are strictly for water flow in/out of the mantle cavity.",
  250: "The paired siphons (incurrent and excurrent) are tube-like extensions of the mantle. Water enters via the incurrent siphon, passes over the gills for gas exchange and filter feeding, then exits via the excurrent siphon. They are not feet, ears, or the anus/mouth.",
  251: "The posterior end of a clam is where the siphons emerge — the end that sticks out of sediment to draw and expel water. The umbo (beak) marks the anterior/dorsal side. Clams orientate with the umbo up and posterior facing the water column.",
  252: "The foot is a muscular wedge used for digging into sediment (burrowing), anchoring the clam in place, and slow locomotion. It is not involved in reproduction (gonads/siphons) or feeding (gills/labial palps).",
  253: "The clam heart lies in the pericardial cavity adjacent to the ostium — the opening through which hemolymph enters the heart chambers. It pumps open-circulatory hemolymph to the gills and body tissues. It is not the kidneys, mouth, or rectum.",
  254: "The intestine and rectum run from the stomach through the pericardial cavity (the rectum literally passes through the ventricle in bivalves) and exit as the anus near the excurrent siphon. It is distinct from gills, gonads, mouth, and siphons.",
  255: "The umbo is the beak-like protrusion at the oldest, most anterior-dorsal part of the shell — where shell growth originally began. Clams have no distinct head. The umbo is not the shell as a whole, the ventral side, or a head.",
  256: "The mantle is a thin tissue sheet lining the inside of each shell valve; it secretes the calcium carbonate shell. The space it encloses is the mantle cavity. It is distinct from gonads, gills, digestive gland, foot, and intestine.",
  257: "The foot is the muscular, tongue- or hatchet-shaped burrowing organ that extends from the visceral mass to dig into substrate. It is not the mantle or gills.",
  258: "The digestive gland (hepatopancreas) is the large dark organ surrounding the stomach. It produces digestive enzymes and absorbs nutrients from digested food. It is distinct from the heart, gonads, intestine/rectum, mantle cavity, foot, and gills.",
  259: "The gills (ctenidia) serve two roles: gas exchange and filter feeding. Ciliated gill surfaces trap suspended food particles (phytoplankton, detritus) from incurrent water and transport them toward the mouth. Gills are not the mantle, gonads, or digestive gland.",
  260: "The adductor muscle pulls the two shell valves tightly shut for defense against predators and desiccation. The shell opens passively via an elastic ligament when the adductor relaxes — the muscle only closes, never opens. It does not dig, feed, or open the shell.",
  261: "Gills serve double duty: gas exchange and filter feeding. Cilia on gill surfaces create water currents that trap suspended food particles and move them toward the mouth via the labial palps. Gills are not gonads, kidneys, or swimming organs.",
  262: "The labial palps are paired lip-like flaps flanking the mouth. They receive food-laden mucus strings from the gills and sort particles — directing suitable food into the mouth and rejecting debris. They are not the mantle, gills, anus, heart, or foot.",
  263: "The labial palps act as lips and food-sorting organs: they receive particles collected by gill cilia and direct acceptable food into the mouth while rejecting oversized debris. They are not gills (which collect food), kidneys (waste excretion), anus, or heart.",
  264: "The foot is the muscular burrowing/locomotion organ — typically tongue- or hatchet-shaped in bivalves — that extends from the visceral mass to dig into sediment. It is distinct from gonads, digestive gland, gills, intestine/rectum, mantle, and heart.",
  265: "The gonads produce gametes (eggs and sperm). Clams are broadcast spawners, releasing eggs and sperm into the water column for external fertilization. Clams can be male, female, or hermaphroditic depending on species. The gonads are not the digestive gland, heart, or intestine.",

  // ── TAXONOMY ID — CNIDARIA CLASSES (270–277) ─────────────────────────────────
  270: "Aurelia aurita is the moon jelly, the Class Scyphozoa lab specimen. Key ID features: bell-shaped medusa with 4-fold (tetramerous) symmetry, 4 horseshoe-shaped gonads visible through the bell, and frilly oral arms. Scyphozoa = 'cup animals' — the true jellyfish, medusa-dominant with a small or reduced polyp stage.",
  271: "Hydra is a freshwater polyp (Class Hydrozoa) with no medusa in its life cycle, but the class as a whole exhibits BOTH polyp and medusa forms. The Portuguese man-of-war is a colonial hydrozoan — not a single organism but a siphonophore colony of specialized polyp and medusa zooids. Key: Hydrozoa is the only cnidarian class with a truly colonial lifestyle.",
  272: "Sea anemones, reef corals, and sea pens all belong to Class Anthozoa ('flower animals'). Anthozoans are ENTIRELY polyp — a medusa stage is completely absent from the life cycle. They are the most species-rich cnidarian class. Corals secrete calcium carbonate skeletons that form coral reefs.",
  273: "Box jellyfish (Class Cubozoa) are named for their distinctive cube-shaped (cuboid) bell. They are the most venomous cnidarians, with complex eyes (including lensed eyes) unique among cnidarians. They are NOT a lab specimen but you must know the class exists.",
  274: "Anthozoa is the only cnidarian class that exists ONLY as a polyp — there is NO medusa stage, ever. Compare: Scyphozoa (medusa dominant), Hydrozoa (both forms), Cubozoa (cube medusa). Memory hook: 'Antho' = flower, and sea anemones look like flowers — they are always sessile polyps.",
  275: "Hydrozoa exhibits BOTH the polyp and medusa forms. Hydra itself is polyp-only, but most hydrozoans (like Obelia) have a colonial polyp stage that buds off free-swimming medusae. The Portuguese man-of-war is an extreme hydrozoan — a colony of both polyp-type and medusa-type zooids.",
  276: "Scyphozoa = 'true jellyfish' — medusa is the dominant, long-lived form, while the polyp (scyphistoma) is small and short-lived. Aurelia aurita is the lab example. Key stats: 4-fold symmetry, 4 gonads, oral arms. Compare Cubozoa (cube medusa) vs. Scyphozoa (saucer/bell medusa).",
  277: "Cubozoa ('box animals') are identified by: (1) cuboid bell shape with four flat sides, (2) one or more complex eyes per side, (3) the most potent cnidarian venom (box jellyfish like Chironex can be lethal). They are not a lab specimen in this course, but distinguish them from Scyphozoa (round bell, less venomous).",

  // ── TAXONOMY ID — PLATYHELMINTHES CLASSES (278–285) ──────────────────────────
  278: "Dugesia tigrina is THE planarian — the free-living flatworm in Class Turbellaria. Key features: cross-eyed appearance (2 eyespots detecting light direction), auricles (ear-like projections), ability to regenerate from small pieces, and freshwater habitat. Turbellaria are the only free-living (non-parasitic) flatworms.",
  279: "Taenia (tapeworms) are Class Cestoda. Three-part ID: (1) scolex — the 'head' with hooks (rostellum) and suckers for attachment to intestinal wall; (2) neck — zone of growth; (3) strobila — chain of proglottids (body segments), each a self-contained reproductive unit. Critically: Cestoda have NO gut — they absorb nutrients entirely through the tegument (outer body wall).",
  280: "Fasciola hepatica (liver fluke) = Class Trematoda. Key features: leaf-shaped body, oral sucker (around mouth) + ventral sucker (acetabulum for attachment), endoparasitic lifestyle in liver bile ducts of sheep/cattle. Schistosoma (blood fluke) is another important trematode (causes schistosomiasis).",
  281: "Turbellaria are the only free-living (non-parasitic) class in Platyhelminthes. They live in freshwater (mostly) or marine habitats, crawl using cilia on the ventral surface, and have an incomplete gut with one opening. Dugesia tigrina is the lab representative.",
  282: "Cestoda (tapeworms) are the only flatworms with NO digestive tract whatsoever. They evolved to live entirely inside host intestines, absorbing pre-digested nutrients through their highly modified tegument. The scolex anchors the worm; proglottids each contain complete sets of male and female reproductive organs.",
  283: "Trematoda (flukes) are identified by TWO suckers: (1) oral sucker surrounding the mouth and (2) ventral sucker (acetabulum) for anchoring to host tissue. They have an incomplete gut (like all flatworms) and a complex life cycle involving one or more intermediate hosts (often snails).",
  284: "Schistosoma and Fasciola are both Trematoda (flukes). Schistosoma = blood fluke causing schistosomiasis; Fasciola = liver fluke infecting bile ducts. Both have the diagnostic two-sucker body plan. Note: Schistosoma is unusual — it has separate sexes (most trematodes are hermaphroditic).",
  285: "Cestoda tapeworms are built from repeating proglottid units. Each proglottid contains both testes and ovaries (hermaphroditic). Gravid (mature) proglottids are filled with fertilized eggs and are shed in feces. The scolex holds the worm in place — without it the worm cannot survive even if the strobila is removed.",

  // ── TAXONOMY ID — ANNELIDA CLASSES (286–292) ─────────────────────────────────
  286: "Nereis virens (clamworm / ragworm) = Class Polychaeta. ID features: parapodia (paddle-like lateral appendages bearing bundles of many setae/bristles), eversible pharynx with jaws for predation, marine habitat. 'Polychaeta' = many bristles. Parapodia also function as gills and locomotion paddles.",
  287: "Lumbricus terrestris = Class Oligochaeta. Key features: clitellum (prominent mucus-secreting band on segments 32–37, used in reproduction), few setae per segment (no parapodia), 5 pairs of aortic arches ('hearts') in segments 7–11, terrestrial/freshwater. 'Oligochaeta' = few bristles.",
  288: "Hirudo medicinalis (medicinal leech) = Class Hirudinea. Key features: anterior sucker (around mouth) + posterior sucker (for attachment), NO setae (unique among annelids), fixed number of 34 body segments, freshwater or moist terrestrial. Leeches are Clitellata (have a clitellum used in reproduction), like earthworms.",
  289: "Polychaeta are the dominant MARINE annelids. Parapodia are paired, unjointed lateral appendages — each bearing many setae (bristles). Parapodia serve multiple functions: locomotion, gas exchange (act as gills), and sensory reception. The everted pharynx with chitinous jaws is used for predation.",
  290: "Hirudinea (leeches) are unique among annelids: (1) NO setae — smooth body surface, (2) anterior sucker around the mouth + posterior sucker for gripping, (3) fixed body segment count (34), (4) members of Clade Clitellata (share clitellum with earthworms). Many are ectoparasites; some are free-living predators.",
  291: "Clade Clitellata unites Oligochaeta (earthworms) + Hirudinea (leeches) based on the shared derived character of a CLITELLUM — a thickened glandular band of segments that secretes a mucous cocoon for egg deposition. Both classes lack parapodia (unlike Polychaeta). Polychaeta is NOT Clitellata.",
  292: "Oligochaeta = 'few bristles' (Greek). Compared to polychaetes: fewer setae per segment (typically 4 per segment, no parapodia), terrestrial or freshwater, hermaphroditic, clitellum present. Lumbricus terrestris is THE lab specimen — know its anatomy cold.",

  // ── TAXONOMY ID — MOLLUSCA CLASSES (293–300) ─────────────────────────────────
  293: "Gastropoda ('stomach-foot') = snails and slugs. Key features: single spiral shell in snails (slugs lost it secondarily), torsion (180° twisting of visceral mass during development), radula (file-like feeding organ). Slugs demonstrate the pneumostome — a respiratory opening on the right side of the mantle.",
  294: "Bivalvia ('two valves') = clams, oysters, mussels, scallops. Key features: TWO hinged shell valves, NO radula (unique — they are filter feeders), gills (ctenidia) for both gas exchange and filter feeding, adductor muscle(s) to close shell. Clam dissection is a major lab component.",
  295: "Cephalopoda ('head-foot') = squid, octopus, nautilus, cuttlefish. Loligo/Doryteuthis = market squid. Key features: 8 arms + 2 tentacles (in squid), internal pen (gladius), ink sac, siphon for jet propulsion, highly developed eyes and nervous system, radula + beak. Most have reduced or internal shell.",
  296: "Polyplacophora ('bearer of many plates') = chitons. The 8 overlapping dorsal shell plates are the defining feature — no other mollusk has this. Chitons also have a radula, a muscular foot for clinging to rocks, and a girdle surrounding the plates. They are demonstration-only in lab (not dissected).",
  297: "Bivalvia is the ONLY mollusk class without a radula. All other classes (Gastropoda, Cephalopoda, Polyplacophora, Scaphopoda) possess a radula — a file-like ribbon of teeth used for scraping food. Bivalves are suspension/filter feeders and have no need for a radula.",
  298: "Chitons (Polyplacophora) are identified by: 8 overlapping dorsal shell plates (= 'many plates'), oval body, girdle around edge, radula, and strong muscular foot. They cling to intertidal rocks. In lab, they are demonstration specimens. No other mollusk has 8 shell plates.",
  299: "Cephalopoda includes squid (Loligo), octopus, nautilus, and cuttlefish. They are the most neurologically advanced invertebrates, with the largest brain-to-body ratio among invertebrates, sophisticated eyes (convergent with vertebrate eyes), and complex behaviors. Shell is internal (squid pen), reduced (cuttlebone), or absent (octopus).",
  300: "Bivalvia are identified by: (1) two hinged shell valves connected by a ligament and adductor muscles, (2) absence of radula — all are filter feeders using ciliated gills, (3) laterally compressed body. Clam, oyster, mussel, scallop, and quahog are all bivalves.",

  // ── TAXONOMY ID — ARTHROPODA SUBPHYLA & CLASSES (301–312) ────────────────────
  301: "Arachnida (Subphylum Chelicerata) = spiders, scorpions, ticks, mites, harvestmen. Key ID: 8 legs (4 pairs), body divided into cephalothorax (prosoma) + abdomen (opisthosoma), NO antennae, chelicerae (fang-like mouthparts), pedipalps. Ticks are arachnids NOT insects — this is a common exam mistake.",
  302: "Malacostraca = the largest, most diverse crustacean class. Includes lobsters, crabs, crayfish, shrimp, krill, and pill bugs (isopods). Crayfish are Order Decapoda (10 legs); pill bugs are Order Isopoda. Key: Crustacea have 2 pairs of antennae and breathe via gills.",
  303: "Class Insecta (Subphylum Hexapoda) is defined by: 6 legs (3 pairs on thorax), 3 body regions (head + thorax + abdomen), 1 pair of antennae, tracheal system for gas exchange. Insects are the most species-rich class of animals on Earth.",
  304: "Chilopoda = centipedes (Subphylum Myriapoda). Key: ONE pair of legs per body segment, elongated flattened body, 1 pair antennae, predatory — the first trunk appendages are modified into venomous forcipules (fang-like claws). Quick count trick: centipedes always have an ODD number of leg-bearing segments.",
  305: "Diplopoda = millipedes (Subphylum Myriapoda). Key: TWO pairs of legs per body segment (diplosegments = two fused segments), cylindrical body, detritivores (eat decaying plant matter), defensive coiling and chemical secretions. Contrast with centipedes: millipedes have 2 pairs/segment, are herbivores/detritivores, and are cylindrical.",
  306: "Maxillopoda = barnacles + copepods (Subphylum Crustacea). Barnacles are sessile crustaceans — they stand on their heads and kick food into their mouths with their legs (cirri). Copepods are the most abundant multicellular animals on Earth (marine zooplankton). Both have highly reduced/modified appendages compared to typical crustaceans.",
  307: "Merostomata = horseshoe crabs — a 'living fossil' unchanged for ~450 million years. Key features: large horseshoe-shaped carapace, 10 walking legs + chelicerae, cephalothorax + abdomen + pointed telson (tail spine), book gills for gas exchange. NOT a true crab (Malacostraca) — it is in Subphylum Chelicerata.",
  308: "Arachnida has 8 legs (4 pairs). This immediately distinguishes arachnids from insects (6 legs / 3 pairs) and crustaceans (10 legs in decapods). Memory: spider = 8 legs = arachnid. Ticks (8 legs as adults) and scorpions (8 legs) are also arachnids, not insects.",
  309: "Chelicerata = the chelicerate subphylum — characterized by chelicerae (fang/pincer-like mouthparts) instead of antennae. Includes Arachnida (spiders, scorpions, mites, ticks), Merostomata (horseshoe crabs), and Pycnogonida (sea spiders). No antennae = Chelicerata. Antennae present = Crustacea, Hexapoda, or Myriapoda.",
  310: "Crustacea = the crustacean subphylum, defined by: (1) TWO pairs of antennae (unique among arthropods — all others have 0 or 1 pair), (2) gills for gas exchange, (3) typically aquatic. Includes Malacostraca (crayfish, crabs), Maxillopoda (barnacles, copepods), and more.",
  311: "Isopoda = pill bugs / roly-polies / woodlice. Despite living on land, pill bugs are crustaceans in Order Isopoda, Class Malacostraca — not insects. They breathe through gill-like pleopods and require moisture. 'Iso' = equal, 'poda' = feet — all legs are similar in size.",
  312: "Decapoda means 'ten feet' — 10 walking legs (5 pairs). Crayfish (Procambarus) are the lab specimen: 5 pairs of walking legs (pereopods), with the first pair enlarged into chelipeds (claws). Also includes lobsters, crabs, shrimp, and prawns. Order Decapoda is within Class Malacostraca, Subphylum Crustacea.",

  // ── TAXONOMY ID — INSECTA ORDERS (313–324) ───────────────────────────────────
  313: "Coleoptera ('sheath-winged') = beetles. The LARGEST insect order by species count (~400,000 species). Diagnostic: front wings (forewings) are hardened into elytra — non-functional protective sheaths covering the folded membranous hind wings. Elytra meet in a straight line down the middle. Examples: ladybugs, weevils, fireflies, dung beetles.",
  314: "Diptera ('two-winged') = flies. Diagnostic: only ONE functional pair of wings (the front pair); hind wings are reduced to club-shaped halteres that function as gyroscopes for flight stabilization. Examples: housefly, mosquito, fruit fly (Drosophila), horsefly, crane fly. Mosquitoes are dipterans, not true 'bugs.'",
  315: "Lepidoptera ('scale-winged') = butterflies and moths. Diagnostic: wings covered in overlapping scales (modified flattened hairs) — the powder left on fingers when touching a wing. Also: coiled proboscis for nectar feeding. Butterflies (typically diurnal, clubbed antennae) and moths (typically nocturnal, feathered antennae) are both Lepidoptera.",
  316: "Hymenoptera ('membrane-winged') = bees, wasps, and ants. Diagnostic: 4 transparent membranous wings hooked together in flight (fore- and hindwings coupled by hamuli). Ants are wingless (except reproductive castes) but are still Hymenoptera. High sociality, eusociality, and haplodiploidy (for sex determination) are hallmarks.",
  317: "Orthoptera ('straight-winged') = grasshoppers, crickets, katydids. Diagnostic: enlarged hind legs for jumping, front wings (tegmina) are slightly leathery / straight, hind wings are large and membranous, fold fan-like. The grasshopper is THE lab dissection insect in this course. 'Orthoptera' = straight wings.",
  318: "Hemiptera ('half-winged') = true bugs. Diagnostic: front wings (hemelytra) are half-leathery at the base and half-membranous at the tip — this 'half-and-half' wing is unique to this order. Also: piercing-sucking mouthparts (stylets forming a tube for liquid feeding). Examples: stink bugs, bed bugs, aphids, cicadas, assassin bugs.",
  319: "Coleoptera (beetles) have elytra — hardened front wings that meet in a straight midline seam and protect the folded membranous hind wings underneath. When a beetle flies, it raises the elytra and extends the hind wings. The elytra are NOT used for flight — only for protection. This is the diagnostic feature that defines Order Coleoptera.",
  320: "Diptera halteres are vestigial hind wings — reduced to small, knob-shaped structures behind the functional forewings. They vibrate at the same frequency as the wings and function as gyroscopes, providing information about rotational motion during flight. Removing halteres causes uncontrolled flight. No other insect order has halteres.",
  321: "Lepidoptera wing scales are tiny, flattened, pigmented hairs covering the wing surface in overlapping rows. They create wing colors and patterns through both pigmentation and structural coloration (iridescence). The scales rub off as 'wing dust.' This is the diagnostic feature of Lepidoptera — no other insect order has scaly wings.",
  322: "Coleoptera = 'koleos' (sheath) + 'pteron' (wing) = sheath-winged. The sheath = elytra. Beetles are the most species-rich order of any organism on Earth (~25% of all known animal species are beetles). The hardened elytra protect against desiccation and physical damage.",
  323: "Lepidoptera = 'lepis' (scale) + 'pteron' (wing) = scale-winged. This describes the microscopic overlapping scales that cover both wings of all butterflies and moths. Scales produce color patterns for camouflage, mate attraction, and warning (aposematism in toxic species like monarch butterflies).",
  324: "Diptera = 'di' (two) + 'pteron' (wing) = two-winged. The halteres (modified hind wings) serve as balance/gyroscope organs. Flies are the only insects with true halteres. Mosquitoes (Diptera) transmit malaria, dengue, Zika, and other diseases — this order has massive medical importance.",

  // ── TAXONOMY ID — CROSS-PHYLUM SPECIES (325–332) ─────────────────────────────
  325: "Ascaris lumbricoides is the giant human intestinal roundworm — up to 35 cm long. It belongs to Phylum Nematoda (roundworms), which are distinguished from flatworms by: round cross-section (not flat), pseudocoelom (body cavity not lined by mesoderm), complete digestive tract (mouth AND anus), and cuticle (shed during molting). Class designation: nematodes have no formal class in modern taxonomy.",
  326: "Dugesia tigrina = planarian = Phylum Platyhelminthes, Class Turbellaria. Turbellarians are the ONLY free-living flatworms (all other classes are parasitic). ID features: cross-eyed auriculate head with two simple eyespots (photoreceptors), triangular or spatula-shaped body, ventral cilia for gliding locomotion, incomplete gut (pharynx extends from underside).",
  327: "Aurelia aurita = moon jelly = Phylum Cnidaria, Class Scyphozoa. The moon jelly is the standard lab specimen representing true jellyfish. Key ID: saucer-shaped translucent bell, 4 horseshoe-shaped gonads (visible through the bell), numerous short marginal tentacles, 4 frilly oral arms hanging from the underside.",
  328: "Lumbricus terrestris = common earthworm = Phylum Annelida, Class Oligochaeta. Lab anatomy: anterior end is more pointed, posterior is flattened; clitellum (saddle-like band) on segments 32–37; dorsal blood vessel visible as dark line; prostomium overhangs the mouth. Know: 5 pairs of aortic arches (pseudo-hearts) in segments 7–11.",
  329: "Loligo / Doryteuthis = market squid = Phylum Mollusca, Class Cephalopoda. Lab anatomy: 8 arms + 2 longer tentacles; mantle (muscular body wall); siphon (funnel for jet propulsion); internal gladius (pen = vestigial shell); ink sac; paired fins. Distinguish: octopus = 8 arms, no tentacles, no pen; squid = 8 arms + 2 tentacles, pen present.",
  330: "Nereis virens = common name is clamworm (also ragworm or sandworm). It is a polychaete annelid in Class Polychaeta. The name 'clamworm' reflects its use as fishing bait (it is found in clam flats). 'Ragworm' refers to its tattered-looking parapodia. It has an eversible pharynx armed with chitinous jaws for predatory feeding.",
  331: "Hirudo medicinalis = medicinal leech = Phylum Annelida, Class Hirudinea. Used for centuries to treat inflammation, venous congestion, and reattached digits (its saliva contains hirudin, an anticoagulant). ID: smooth body (NO setae), 34 segments, oral sucker around mouth, large posterior sucker for gripping. Class Hirudinea is part of Clade Clitellata.",
  332: "Fasciola hepatica = liver fluke = Phylum Platyhelminthes, Class Trematoda. 'Liver fluke' = parasitic in the bile ducts of sheep, cattle, and humans. 'Fasciola' = little band (leaf-shaped body). Life cycle involves two hosts: snail (intermediate) → mammal (definitive). Diagnosis: leaf-shaped body, oral sucker at anterior tip, large ventral sucker (acetabulum) just behind it.",

};
